core/urls.py
"""Core urls."""

records/urls.py
"""Configuração de urls da aplicação registros."""

from django.conf.urls import url

from .views import CompositionSearchView, ExportToExcelView, InsumSearchView

urlpatterns = [
    url(r'^insum_search$', InsumSearchView.as_view(), name='insum_search'),
    url(r'^composition_search$', CompositionSearchView.as_view(), name='composition_search'),
    url(r'^export_to_excel', ExportToExcelView.as_view(), name='export_to_excel'),
]

sinapi/urls.py
"""Módulo de configuração de urls do projeto."""

from allauth import urls as allauth_urls
from core.views import UserViewSet
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.admin import site
from records import urls as records_urls
from records.views import RecordViewSet
from rest_auth import urls as rest_auth_urls
from rest_framework.routers import DefaultRouter

from .views import IndexView

router = DefaultRouter()
router.register('users', UserViewSet)
router.register('records', RecordViewSet)

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^records/', include(records_urls, namespace='records')),
    url(r'^contas/', include(allauth_urls)),
    url(r'^rest_auth/', include(rest_auth_urls)),
    url(r'^api/v1/', include(router.urls, namespace='v1')),
    url(r'^admin/', include(site.urls)),
]

# media files in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
"""Modelos da aplicação core."""

from django.contrib.auth.models import AbstractUser

from model_utils.models import TimeStampedModel


class User(TimeStampedModel, AbstractUser):

    """Usuário base do projeto."""

    class Meta:
        verbose_name = 'Usuário'

records/models.py
"""Registros SINAPI."""

from django.db.models import CharField, TextField, DecimalField, IntegerField
from model_utils.models import TimeStampedModel

RECORD_CHOICES = [('insum', 'Insumo'), ('composition', 'Composição')]


class Record(TimeStampedModel):

    """Um registro no SINAPI podendo ser classificado como insumo ou composição."""

    code = CharField(max_length=15, primary_key=True)
    description = TextField()
    unity = CharField(max_length=15)
    origin = CharField(max_length=15)
    price = DecimalField(decimal_places=2, max_digits=20)
    month = IntegerField()
    year = IntegerField()
    type = CharField(max_length=15, choices=RECORD_CHOICES)

    def __str__(self):
        """toString."""
        return '[code={}][description={}][unity={}][origin={}][price={}][date={}/{}]'.format(
            self.code,
            self.description,
            self.unity,
            self.origin,
            self.price,
            self.month,
            self.year,
        )

    class Meta:
        ordering = ('code',)

records/forms.py
"""Formulários da aplicação registros."""

from django.forms import CharField, Form
from django.http import HttpResponse

from .models import Record
from .pdf2db.converter import save_records_to_excel


class ExportToExcelForm(Form):

    """Formulário responsável por gerar arquivos excel a partir de registros."""

    # conjunto de codes separados por vígula.
    query = CharField()
    sheet_name = CharField(required=False)

    def save(self):
        """Gera o conteúdo do arquivo excel."""
        query = self.cleaned_data['query'].split(',')
        sheet_name = self.cleaned_data['sheet_name'] or 'Planilha'
        response = HttpResponse(
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
        response['Content-Disposition'] = 'attachment;filename="{}.xlsx"'.format(sheet_name)
        save_records_to_excel(Record.objects.filter(code__in=query), response)
        return response

core/views.py
"""Views da aplicação core."""

from django.contrib.auth import get_user_model
from rest_framework.permissions import IsAdminUser
from rest_framework.viewsets import ModelViewSet

from .serializers import UserSerializer


class UserViewSet(ModelViewSet):

    """User viewset."""

    serializer_class = UserSerializer
    permission_classes = (IsAdminUser,)
    queryset = get_user_model().objects.all()

records/views.py
"""Views da aplicação registros."""

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import View
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin
from rest_framework.permissions import IsAuthenticated
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.viewsets import GenericViewSet

from .forms import ExportToExcelForm
from .models import Record
from .serializers import RecordSerializer


class InsumSearchView(APIView):

    """Página de consulta de insumos."""

    renderer_classes = [TemplateHTMLRenderer]
    permission_classes = [IsAuthenticated]
    template_name = 'records/insum.html'

    def get(self, request):
        """Obtém a página."""
        return Response()


class CompositionSearchView(InsumSearchView):

    """Página para consulta de composições."""

    template_name = 'records/composition.html'


class RecordViewSet(ListModelMixin, RetrieveModelMixin, GenericViewSet):

    """Permite listar e visualizar registros via api."""

    serializer_class = RecordSerializer
    queryset = Record.objects.all()
    permission_classes = [IsAuthenticated]
    search_fields = ('code', 'description', 'unity', 'origin', 'price')
    filter_fields = ('type', 'month', 'year')


class ExportToExcelView(LoginRequiredMixin, View):

    """Gera arquivos excel a partir de registros do banco de dados."""

    def post(self, request, *args, **kwargs):
        """Envia os bytes do arquivo excel para o cliente."""
        form = ExportToExcelForm(request.POST)
        if form.is_valid():
            return form.save()

sinapi/views.py
"""Módulo contém views genéricas ou globais ao projeto."""

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class IndexView(LoginRequiredMixin, TemplateView):

    """
    Página base da aplicação.

    Esta página contém a infraestrutura SPA (Single Page Application): scripts, estilos, etc.
    """

    template_name = 'base.html'

sinapi/templates/base.html
<!DOCTYPE html>{% load static from staticfiles %}{% load gravatar_url from core_tags %}
<html lang="en" ng-app="sinapi">
<head>
  {% block meta %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  {% endblock meta %}

  <title>{% block title %}Bem vindo{% endblock title %}</title>

  {% block bower_css %}
    <!-- bower:css -->
    <link rel="stylesheet" href="{% static 'vendor/angular-toastr/dist/angular-toastr.css' %}" />
    <link rel="stylesheet" href="{% static 'vendor/angular-busy/dist/angular-busy.css' %}" />
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'vendor/Ionicons/css/ionicons.css' %}" />
    <link rel="stylesheet" href="{% static 'vendor/angular-ui-grid/ui-grid.css' %}" />
    <!-- endbower -->
  {% endblock bower_css %}

  {% block inject_css %}
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/skins/skin-black.min.css' %}">
    <!-- endinject -->
  {% endblock inject_css %}

  {% block bower_js %}
    <!-- bower:js -->
    <script src="{% static 'vendor/jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'vendor/angular/angular.js' %}"></script>
    <script src="{% static 'vendor/angular-resource/angular-resource.js' %}"></script>
    <script src="{% static 'vendor/angular-ui-router/release/angular-ui-router.js' %}"></script>
    <script src="{% static 'vendor/angular-toastr/dist/angular-toastr.tpls.js' %}"></script>
    <script src="{% static 'vendor/angular-animate/angular-animate.js' %}"></script>
    <script src="{% static 'vendor/angular-busy/dist/angular-busy.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/angular-bootstrap/ui-bootstrap-tpls.js' %}"></script>
    <script src="{% static 'vendor/angular-ui-grid/ui-grid.js' %}"></script>
    <script src="{% static 'vendor/lodash/lodash.js' %}"></script>
    <script src="{% static 'vendor/br-validations/releases/br-validations.js' %}"></script>
    <script src="{% static 'vendor/string-mask/src/string-mask.js' %}"></script>
    <script src="{% static 'vendor/angular-input-masks/angular-input-masks-standalone.min.js' %}"></script>
    <script src="{% static 'vendor/angular-translate/angular-translate.js' %}"></script>
    <script src="{% static 'vendor/angular-locale-pt-br/angular-locale_pt-br.js' %}"></script>
    <!-- endbower -->
  {% endblock bower_js %}
  
  {% block inject_js %}
    <!-- inject:js -->
    <script src="{% static 'app/app.module.js' %}"></script>
    <script src="{% static 'app/admin.lite.min.js' %}"></script>
    <script src="{% static 'app/app.config.js' %}"></script>
    <script src="{% static 'app/app.routes.js' %}"></script>
    <script src="{% static 'app/mainCtrl.js' %}"></script>
    <script src="{% static 'app/core/confirmModalService.js' %}"></script>
    <script src="{% static 'app/core/submit.directive.js' %}"></script>
    <script src="{% static 'app/records/RecordResource.js' %}"></script>
    <script src="{% static 'app/records/compositionCtrl.js' %}"></script>
    <script src="{% static 'app/records/insumCtrl.js' %}"></script>
    <!-- endinject -->
  {% endblock inject_js %}
  
  <script>
    {% block script %}
      var app = angular.module('sinapi');
      app.constant('cgBusyDefaults', {
        templateUrl: '{% static "templates/angular-busy.html" %}',
        message: 'Aguarde...'
      });
      <!-- urls -->
      app.constant('loginURL', '{% url "account_login" %}');
      app.constant('logoutURL', '{% url "account_logout" %}');
      app.constant('recordAPIURL', '{% url "v1:record-list" %}');

      <!-- templates -->
      app.constant('confirmModalTemplate', '{% static "app/core/confirm-modal.html" %}');
      app.constant('insumSearchURL', '{% url "records:insum_search" %}');
      app.constant('compositionSearchURL', '{% url "records:composition_search" %}');
    {% endblock script %}
  </script>
</head>
<body ng-controller="mainCtrl as main" class="{% block body_class %}hold-transition skin-black sidebar-mini{% endblock body_class %}">
  {% block body %}
    <div class="wrapper">

      <!-- Main Header -->
      <header class="main-header">

        <!-- Logo -->
        <a ui-sref="index" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>S</b>API</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>SIN</b>API</span>
        </a>

        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- User Account Menu -->
              <li class="dropdown user user-menu">
                <!-- Menu Toggle Button -->
                <a href="" class="dropdown-toggle" data-toggle="dropdown">
                  <!-- The user image in the navbar-->
                  <img src="{% gravatar_url user.email %}" class="user-image" alt="User Image">
                  <!-- hidden-xs hides the username on small devices so only the image appears. -->
                  <span class="hidden-xs">{{ user.username.capitalize }}</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- The user image in the menu -->
                  <li class="user-header">
                    <img src="{% gravatar_url user.email %}" class="img-circle" alt="User Image">
                    <p>
                      {{ user.get_full_name.title }}
                      <small>Desde {{ user.created }}</small>
                    </p>
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-right">
                      <a ng-click="main.logout()" class="btn btn-default btn-flat">Logout</a>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">

          <!-- Sidebar user panel (optional) -->
          <div class="user-panel">
            <div class="pull-left image">
              <img src="{% gravatar_url user.email %}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
              <p>{{ user.get_full_name.title }}</p>
              <!-- Status -->
              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
          </div>

          <!-- Sidebar Menu -->
          <ul class="sidebar-menu">
            <li class="header">Relatórios por mês e ano.</li>
            <!-- Optionally, you can add icons to the links -->
            <li class="treeview" ng-class="{active: $state.includes('record')}">
              <a href=""><i class="fa fa-link"></i> <span>Outubro de 2015</span> <i class="fa fa-angle-left pull-right"></i></a>
              <ul class="treeview-menu">
                <li ui-sref-active="active"><a ui-sref="record.insum">Insumos</a></li>
                <li ui-sref-active="active"><a ui-sref="record.composition">Composições</a></li>
              </ul>
            </li>
          </ul><!-- /.sidebar-menu -->
          </ul><!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">

        <!-- Main content -->
        <section class="content">

          <!-- Your Page Content Here -->
          <div ui-view=""></div>

        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

      <!-- Main Footer -->
      <footer class="main-footer">
        <!-- To the right -->
        <div class="pull-right hidden-xs">
          Tabelas SINAPI
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; 2015 <a href="#">Company</a>.</strong> All rights reserved.
      </footer>
      
    </div><!-- ./wrapper -->
  {% endblock body %}
</body>
</html>

sinapi/templates/records/composition.html
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12 box box-solid">
      <div class="box-header with-border">
        <h3 class="box-title">Busca de Composições.</h3>
      </div>

      <div class="box-body">
        <div class="row form-group">
          <div class="col-lg-4">
            <form name="saerchCompositionForm" novalidate>{% csrf_token %}
              <input id="searchComposition" type="text" name="search" ng-model="vm.searchQuery"
                  class="form-control" ng-keyup="vm.searchComposition()"
                  placeholder="Digite para buscar uma composição." required>
            </form>
          </div>
          <form name="exportToExcelForm" action="{% url 'records:export_to_excel' %}" method="post"
              ng-submit="vm.exportToExcel()">{% csrf_token %}
            <input type="hidden" name="query" value="[[ vm.excelQuery ]]" />
            <button class="btn btn-success" type="submit" ng-show="vm.gridOptions.data.length > 0">
              <i class="fa fa-file-excel-o fw"></i> Excel
            </button>
          </form>
        </div>

        <div class="row" cg-busy="vm.searchCompositionPromise">
          <div class="col-lg-12">
            <div ui-grid="vm.gridOptions" ui-grid-pagination ui-grid-resize-columns style="padding: 0"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/ng-template" id="compositionPrice.html">
  <div class="ui-grid-cell-contents">[[ row.entity.price|currency ]]</div>
</script>

sinapi/templates/records/insum.html
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12 box box-solid">
      <div class="box-header with-border">
        <h3 class="box-title">Busca de Insumos.</h3>
      </div>

      <div class="box-body">
        <div class="row form-group">
          <div class="col-lg-4">
            <form name="saerchInsumForm" novalidate>{% csrf_token %}
              <input id="searchInsum" type="text" name="search" ng-model="vm.searchQuery" class="form-control"
                  ng-keyup="vm.searchInsum()" placeholder="Digite para buscar um insumo." required>
            </form>
          </div>
          <form name="exportToExcelForm" action="{% url 'records:export_to_excel' %}" method="post"
              ng-submit="vm.exportToExcel()">{% csrf_token %}
            <input type="hidden" name="query" value="[[ vm.excelQuery ]]" />
            <button class="btn btn-success" type="submit" ng-show="vm.gridOptions.data.length > 0">
              <i class="fa fa-file-excel-o fw"></i> Excel
            </button>
          </form>
        </div>

        <div class="row" cg-busy="{promise:vm.searchInsumPromise}">
          <div class="col-lg-12">
            <div ui-grid="vm.gridOptions" ui-grid-pagination ui-grid-resize-columns style="padding: 0"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/ng-template" id="insumPrice.html">
  <div class="ui-grid-cell-contents">[[ row.entity.price|currency ]]</div>
</script>